sensor_kit_base_link:
  rslidar_rear:
    x: 0.04
    y: 0.0
    z: 0.03553
    roll: 0.0
    pitch: 0.0
    yaw: 3.141 # 180 degree
  rslidar_right:
    x: 1.5
    y: 0.36
    z: 0.03553
    roll: 0.0
    pitch: 0.0
    yaw: 4.45 # 255 degree
  rslidar_left:
    x: 1.5
    y: -0.36
    z: 0.03553
    roll: 0.0
    pitch: 0.0
    yaw: 1.832 # 105 degree
  rslidar_front:
    x: 1.68
    y: 0.5
    z: 0.03553
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera0/camera_link: # front/center/right
    x: 1.68
    y: 0.0
    z: 0.042
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera1/camera_link: # front/center/left
    x: 1.68
    y: -0.1
    z: 0.042
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera2/camera_link: # rear/center
    x: 0.04
    y: 0.1
    z: 0.042
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera3/camera_link: # front/left
    x: 1.68
    y: -0.4
    z: 0.042
    roll: 0.0
    pitch: 0.0
    yaw: 0.017 # 45 degree
  camera4/camera_link: # front/right
    x: 1.68
    y: 0.4
    z: 0.042
    roll: 0.0
    pitch: 0.0
    yaw: 5.498 # 315 degree
  camera5/camera_link: # rear/left
    x: 0.0
    y: -0.4
    z: 0.042
    roll: 0.0
    pitch: 0.0
    yaw: 2.356 # 135 degree
  camera6/camera_link: # rear/right
    x: 0.0
    y: 0.4
    z: 0.042
    roll: 0.0
    pitch: 0.0
    yaw: 3.927 # 225 degree
  gnss_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
